version: '2'
services:
  mysql-server:
    hostname: mysql-server
    container_name: mysql-server
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    networks:
      zabbix:
        ipv4_address: 172.18.0.2
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/conf:/etc/mysql/conf.d
    command: --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
          
  zabbix-server:
    hostname: zabbix-server-mysql 
    image: zabbix/zabbix-server-mysql:centos-4.2-latest
    restart: always
    networks:
      zabbix:
        ipv4_address: 172.18.0.3
    links:
      - mysql-server:mysql-server
    container_name: zabbix-server
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /data/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /data/zabbix/zabbix-server:/var/lib/zabbix    
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 123456
      ZBX_AGENT: zabbix-agent

  zabbix-web-nginx-mysql:
    hostname: zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    networks:
      zabbix:
        ipv4_address: 172.18.0.4
    links: 
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server
    ports:
      - 80:80
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 123456
      ZBX_SERVER_NAME: zabbix master
      PHP_TZ: Asia/Shanghai

#  zabbix-agent:
#    hostname: zabbix-agent
#    image: zabbix/zabbix-agent:latest
#    restart: always
#    networks:
#      - zabbix
#    container_name: zabbix-agent-1
#    links:
#      - zabbix-server:zabbix-server
#    ports:
#      - 10050:10050
#    environment:
#      ZBX_HOSTNAME: monitor-1
#      ZBX_SERVER_HOST: 172.16.36.130
#      ZBX_SERVER_PORT: 10051
#      ZBX_UNSAFEUSERPARAMETERS: 1

networks:
  zabbix: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
